version: '3'

services:
  mongodb:
    image: mongo:6.0
    ports:
      - 27017:27017
    volumes: 
      - ./bd/MongoDB:/data/db

  mysql:
    image: mysql:8.0.33
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3309:3306
    volumes:
    - ./bd/MYSQL:/var/lib/mysql
  mariadb:
    image: mariadb:10.6.14
    environment:
      - MARIADB_ROOT_PASSWORD=root
    ports:
      - 3307:3306
    volumes:
    - ./bd/MariaDB:/var/lib/mysql

  my_express:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 3000:5000
    environment:
      - MONGO_DB_HOST=mongodb

      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root

      - MARIADB_HOST=mariadb
      - MARIADB_USER=root
      - MARIADB_PASSWORD=root

    volumes:
      - ./server:/servidor
      - /servidor/node_modules

    restart: always
    depends_on:
      - mysql
      - mongodb
      - mariadb
